spring.application.name=hackhub

# Database - Nota il punto prima di /data
spring.datasource.url=jdbc:h2:file:./hackhub/data/Database_hackhub_h2;AUTO_SERVER=TRUE
spring.datasource.username=sa
# Uso 1234 per lanciare velocemente h2 ma occorre mettere password complessa tipo zUby$882! o anche con pi� lettere, cifre e caratteri speciali
# spring.datasource.password=zUby$882!
spring.datasource.password=1234
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false

# JWT
app.jwt.secret=mySuperSecretKey12345678901234567890
app.jwt.expiration-ms=86400000

spring.main.banner-mode=off
spring.shell.interactive.enabled=true

